name: Build
on:
  push:
  
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: .
          build-dir: output
          options: |
            BUILD_TESTS=ON

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: output/tests
